// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close():Promise<void>;

export function GetOS():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function Maximize():Promise<void>;

export function Minimize():Promise<void>;

export function SelectDirectory():Promise<string>;

export function Unmaximize():Promise<void>;
