// Wails runtime placeholder - this file will be auto-generated by Wails
// Run 'wails dev' or 'wails generate module' to regenerate this file

export function EventsOn(eventName: string, callback: (...data: any) => void): () => void {
  console.warn('Wails runtime not initialized');
  return () => {};
}

export function EventsEmit(eventName: string, ...data: any): void {
  console.warn('Wails runtime not initialized');
}

export function LogPrint(message: string): void {
  console.log(message);
}

export function LogTrace(message: string): void {
  console.trace(message);
}

export function LogDebug(message: string): void {
  console.debug(message);
}

export function LogInfo(message: string): void {
  console.info(message);
}

export function LogWarning(message: string): void {
  console.warn(message);
}

export function LogError(message: string): void {
  console.error(message);
}

export function Environment(): Promise<EnvironmentInfo> {
  return Promise.resolve({
    buildType: "dev",
    platform: "unknown",
    arch: "unknown"
  });
}

export interface EnvironmentInfo {
  buildType: string;
  platform: string;
  arch: string;
}

export interface Size {
  w: number;
  h: number;
}

export interface Position {
  x: number;
  y: number;
}
