// Wails Go bindings placeholder - this file will be auto-generated by Wails
// Run 'wails dev' or 'wails generate module' to regenerate this file

export function Greet(arg1: string): Promise<string> {
  return Promise.resolve("Hello " + arg1 + "!");
}

export function GetOS(): Promise<string> {
  return Promise.resolve("browser");
}

export function Minimize(): Promise<void> {
  return Promise.resolve();
}

export function Maximize(): Promise<void> {
  return Promise.resolve();
}

export function Unmaximize(): Promise<void> {
  return Promise.resolve();
}

export function Close(): Promise<void> {
  return Promise.resolve();
}
