// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/agents": {
            "get": {
                "description": "获取所有 Agent 列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agent"
                ],
                "summary": "获取所有 Agent",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Agent"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "创建一个新的 Agent",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agent"
                ],
                "summary": "创建 Agent",
                "parameters": [
                    {
                        "description": "Agent 信息",
                        "name": "agent",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateAgentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Agent"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/agents/type": {
            "get": {
                "description": "根据类型获取 Agent 列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agent"
                ],
                "summary": "按类型获取 Agent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent 类型 (main/sub/custom)",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Agent"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/agents/{id}": {
            "get": {
                "description": "根据 ID 获取 Agent 详情",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agent"
                ],
                "summary": "获取 Agent 详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Agent"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "更新 Agent 信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agent"
                ],
                "summary": "更新 Agent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新内容",
                        "name": "agent",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UpdateAgentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Agent"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除指定 Agent",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agent"
                ],
                "summary": "删除 Agent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/agents/{id}/tools": {
            "post": {
                "description": "为指定 Agent 添加工具",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agent"
                ],
                "summary": "为 Agent 添加工具",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "工具 ID",
                        "name": "tool",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/agents/{id}/tools/{tool_name}": {
            "delete": {
                "description": "从 Agent 中移除指定工具",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agent"
                ],
                "summary": "移除 Agent 工具",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "工具名称",
                        "name": "tool_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/chat/session/{session_id}": {
            "delete": {
                "description": "清空指定会话的所有消息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "清空会话消息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话 ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/chat/stream": {
            "post": {
                "description": "与 AI 进行流式对话，支持工具调用",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "流式聊天",
                "parameters": [
                    {
                        "description": "聊天请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.StreamChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE 流式响应",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/messages": {
            "get": {
                "description": "获取所有消息列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Message"
                ],
                "summary": "获取所有消息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Message"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "创建一条新消息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Message"
                ],
                "summary": "创建消息",
                "parameters": [
                    {
                        "description": "消息信息",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Message"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除指定会话的所有消息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Message"
                ],
                "summary": "删除会话所有消息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话 ID",
                        "name": "session_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/messages/session": {
            "get": {
                "description": "根据会话 ID 获取消息列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Message"
                ],
                "summary": "按会话获取消息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话 ID",
                        "name": "session_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Message"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/messages/type": {
            "get": {
                "description": "根据类型获取消息列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Message"
                ],
                "summary": "按类型获取消息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "消息类型 (user/assistant/system/tool)",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Message"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/messages/{id}": {
            "get": {
                "description": "根据 ID 获取消息详情",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Message"
                ],
                "summary": "获取消息详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "消息 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Message"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "更新消息信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Message"
                ],
                "summary": "更新消息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "消息 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新内容",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UpdateMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Message"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除指定消息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Message"
                ],
                "summary": "删除消息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "消息 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/messages/{id}/feedback": {
            "post": {
                "description": "为消息添加点赞/点踩反馈",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Message"
                ],
                "summary": "添加消息反馈",
                "parameters": [
                    {
                        "type": "string",
                        "description": "消息 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "反馈信息",
                        "name": "feedback",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.AddFeedbackRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Message"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/providers": {
            "get": {
                "description": "获取所有 Provider 列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider"
                ],
                "summary": "获取所有 Provider",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Provider"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "创建一个新的模型提供商配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider"
                ],
                "summary": "创建 Provider",
                "parameters": [
                    {
                        "description": "Provider 信息",
                        "name": "provider",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateProviderRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Provider"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/providers/default": {
            "get": {
                "description": "获取默认的 Provider 配置",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider"
                ],
                "summary": "获取默认 Provider",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Provider"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/providers/{id}": {
            "get": {
                "description": "根据 ID 获取 Provider 详情",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider"
                ],
                "summary": "获取 Provider 详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Provider ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Provider"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "更新 Provider 配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider"
                ],
                "summary": "更新 Provider",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Provider ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新内容",
                        "name": "provider",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UpdateProviderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Provider"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除指定 Provider",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider"
                ],
                "summary": "删除 Provider",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Provider ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/sessions": {
            "get": {
                "description": "获取所有会话列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Session"
                ],
                "summary": "获取所有会话",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Session"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "创建一个新的会话",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Session"
                ],
                "summary": "创建会话",
                "parameters": [
                    {
                        "description": "会话信息",
                        "name": "session",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Session"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/sessions/status": {
            "get": {
                "description": "根据状态获取会话列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Session"
                ],
                "summary": "按状态获取会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话状态 (active/paused/completed/archived)",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Session"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/sessions/{id}": {
            "get": {
                "description": "根据 ID 获取会话详情",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Session"
                ],
                "summary": "获取会话详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Session"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "更新会话信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Session"
                ],
                "summary": "更新会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新内容",
                        "name": "session",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UpdateSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Session"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除指定会话",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Session"
                ],
                "summary": "删除会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/sessions/{id}/config": {
            "get": {
                "description": "获取指定会话的配置",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Session"
                ],
                "summary": "获取会话配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.SessionConfig"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "更新指定会话的配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Session"
                ],
                "summary": "更新会话配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "配置信息",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UpdateSessionConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Session"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/tools": {
            "get": {
                "description": "获取所有工具列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tool"
                ],
                "summary": "获取所有工具",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Tool"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "创建一个新的工具定义",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tool"
                ],
                "summary": "创建工具",
                "parameters": [
                    {
                        "description": "工具信息",
                        "name": "tool",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateToolRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Tool"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/tools/status": {
            "get": {
                "description": "根据状态获取工具列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tool"
                ],
                "summary": "按状态获取工具",
                "parameters": [
                    {
                        "type": "string",
                        "description": "工具状态 (active/inactive/deprecated)",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Tool"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/tools/type": {
            "get": {
                "description": "根据类型获取工具列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tool"
                ],
                "summary": "按类型获取工具",
                "parameters": [
                    {
                        "type": "string",
                        "description": "工具类型 (builtin/custom/mcp)",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Tool"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/tools/{id}": {
            "get": {
                "description": "根据 ID 获取工具详情",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tool"
                ],
                "summary": "获取工具详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "工具 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Tool"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "更新工具信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tool"
                ],
                "summary": "更新工具",
                "parameters": [
                    {
                        "type": "string",
                        "description": "工具 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新内容",
                        "name": "tool",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UpdateToolRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Tool"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除指定工具",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tool"
                ],
                "summary": "删除工具",
                "parameters": [
                    {
                        "type": "string",
                        "description": "工具 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/tools/{id}/config": {
            "put": {
                "description": "更新指定工具的配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tool"
                ],
                "summary": "更新工具配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "工具 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "配置信息",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Tool"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/api/tools/{id}/test": {
            "get": {
                "description": "测试工具定义是否正确加载",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tool"
                ],
                "summary": "测试工具",
                "parameters": [
                    {
                        "type": "string",
                        "description": "工具 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.AddFeedbackRequest": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string",
                    "example": "很有帮助"
                },
                "rating": {
                    "type": "string",
                    "example": "like"
                }
            }
        },
        "controllers.CreateAgentRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "通用助手"
                },
                "instructions": {
                    "type": "string",
                    "example": "你是一个智能助手"
                },
                "is_sub_agent": {
                    "type": "boolean",
                    "example": false
                },
                "model": {
                    "type": "string",
                    "example": "gpt-4"
                },
                "name": {
                    "type": "string",
                    "example": "助手"
                },
                "provider_id": {
                    "type": "string",
                    "example": "provider-001"
                },
                "tools": {
                    "type": "string",
                    "example": "file_read,file_write"
                },
                "type": {
                    "type": "string",
                    "example": "main"
                }
            }
        },
        "controllers.CreateMessageRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "example": "你好"
                },
                "parent_id": {
                    "type": "string",
                    "example": "msg-001"
                },
                "session_id": {
                    "type": "string",
                    "example": "session-001"
                },
                "status": {
                    "type": "string",
                    "example": "completed"
                },
                "type": {
                    "type": "string",
                    "example": "user"
                }
            }
        },
        "controllers.CreateProviderRequest": {
            "type": "object",
            "required": [
                "api_key",
                "base_url",
                "model",
                "name"
            ],
            "properties": {
                "api_key": {
                    "type": "string",
                    "example": "sk-xxx"
                },
                "base_url": {
                    "type": "string",
                    "example": "https://api.openai.com/v1"
                },
                "is_default": {
                    "type": "boolean",
                    "example": true
                },
                "max_tokens": {
                    "type": "integer",
                    "example": 2000
                },
                "model": {
                    "type": "string",
                    "example": "gpt-4"
                },
                "name": {
                    "type": "string",
                    "example": "OpenAI"
                },
                "temperature": {
                    "type": "number",
                    "example": 0.7
                }
            }
        },
        "controllers.CreateSessionRequest": {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string",
                    "example": "新会话"
                }
            }
        },
        "controllers.CreateToolRequest": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string",
                    "example": "system"
                },
                "config": {
                    "type": "string",
                    "example": "{}"
                },
                "desc": {
                    "type": "string",
                    "example": "读取文件内容"
                },
                "example": {
                    "type": "string",
                    "example": "读取 /path/to/file.txt"
                },
                "name": {
                    "type": "string",
                    "example": "file_read"
                },
                "parameters": {
                    "type": "string",
                    "example": "{\"path\": \"string\"}"
                },
                "returns": {
                    "type": "string",
                    "example": "文件内容字符串"
                },
                "type": {
                    "type": "string",
                    "example": "builtin"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "controllers.StreamChatRequest": {
            "type": "object",
            "required": [
                "message",
                "session_id"
            ],
            "properties": {
                "agent_id": {
                    "type": "string",
                    "example": "default"
                },
                "message": {
                    "type": "string",
                    "example": "你好"
                },
                "session_id": {
                    "type": "string",
                    "example": "session-001"
                },
                "work_dir": {
                    "type": "string",
                    "example": "E:\\codes\\project"
                }
            }
        },
        "controllers.UpdateAgentRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "通用助手"
                },
                "instructions": {
                    "type": "string",
                    "example": "你是一个智能助手"
                },
                "is_sub_agent": {
                    "type": "boolean",
                    "example": false
                },
                "model": {
                    "type": "string",
                    "example": "gpt-4"
                },
                "name": {
                    "type": "string",
                    "example": "助手"
                },
                "provider_id": {
                    "type": "string",
                    "example": "provider-001"
                },
                "tools": {
                    "type": "string",
                    "example": "file_read,file_write"
                },
                "type": {
                    "type": "string",
                    "example": "main"
                }
            }
        },
        "controllers.UpdateMessageRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "example": "更新后的内容"
                },
                "feedback_comment": {
                    "type": "string",
                    "example": "很有帮助"
                },
                "feedback_rating": {
                    "type": "string",
                    "example": "like"
                },
                "input_tokens": {
                    "type": "integer",
                    "example": 100
                },
                "output_tokens": {
                    "type": "integer",
                    "example": 200
                },
                "status": {
                    "type": "string",
                    "example": "completed"
                }
            }
        },
        "controllers.UpdateProviderRequest": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string",
                    "example": "sk-xxx"
                },
                "base_url": {
                    "type": "string",
                    "example": "https://api.openai.com/v1"
                },
                "is_default": {
                    "type": "boolean",
                    "example": true
                },
                "max_tokens": {
                    "type": "integer",
                    "example": 2000
                },
                "model": {
                    "type": "string",
                    "example": "gpt-4"
                },
                "name": {
                    "type": "string",
                    "example": "OpenAI"
                },
                "temperature": {
                    "type": "number",
                    "example": 0.7
                }
            }
        },
        "controllers.UpdateSessionConfigRequest": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/models.SessionConfig"
                }
            }
        },
        "controllers.UpdateSessionRequest": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/models.SessionConfig"
                },
                "status": {
                    "type": "string",
                    "example": "active"
                },
                "title": {
                    "type": "string",
                    "example": "我的会话"
                }
            }
        },
        "controllers.UpdateToolRequest": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string",
                    "example": "system"
                },
                "config": {
                    "type": "string",
                    "example": "{}"
                },
                "desc": {
                    "type": "string",
                    "example": "读取文件内容"
                },
                "example": {
                    "type": "string",
                    "example": "读取 /path/to/file.txt"
                },
                "name": {
                    "type": "string",
                    "example": "file_read"
                },
                "parameters": {
                    "type": "string",
                    "example": "{\"path\": \"string\"}"
                },
                "returns": {
                    "type": "string",
                    "example": "文件内容字符串"
                },
                "type": {
                    "type": "string",
                    "example": "builtin"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "models.Agent": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "instructions": {
                    "type": "string"
                },
                "is_sub_agent": {
                    "type": "boolean"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "provider_id": {
                    "type": "string"
                },
                "tools": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/models.AgentType"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "models.AgentType": {
            "type": "string",
            "enum": [
                "main",
                "sub",
                "custom"
            ],
            "x-enum-varnames": [
                "AgentTypeMain",
                "AgentTypeSub",
                "AgentTypeCustom"
            ]
        },
        "models.FeedbackRating": {
            "type": "string",
            "enum": [
                "like",
                "dislike"
            ],
            "x-enum-varnames": [
                "FeedbackRatingLike",
                "FeedbackRatingDislike"
            ]
        },
        "models.JSONTime": {
            "type": "object",
            "properties": {
                "time.Time": {
                    "type": "string"
                },
                "valid": {
                    "description": "用于处理 NULL 值",
                    "type": "boolean"
                }
            }
        },
        "models.Message": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "feedback_at": {
                    "$ref": "#/definitions/models.JSONTime"
                },
                "feedback_comment": {
                    "type": "string"
                },
                "feedback_rating": {
                    "$ref": "#/definitions/models.FeedbackRating"
                },
                "id": {
                    "type": "string"
                },
                "input_tokens": {
                    "type": "integer"
                },
                "output_tokens": {
                    "type": "integer"
                },
                "parent_id": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/models.MessageStatus"
                },
                "type": {
                    "$ref": "#/definitions/models.MessageType"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "models.MessageStatus": {
            "type": "string",
            "enum": [
                "sending",
                "completed",
                "failed",
                "streaming"
            ],
            "x-enum-varnames": [
                "MessageStatusSending",
                "MessageStatusCompleted",
                "MessageStatusFailed",
                "MessageStatusStreaming"
            ]
        },
        "models.MessageType": {
            "type": "string",
            "enum": [
                "user",
                "assistant",
                "system",
                "tool"
            ],
            "x-enum-varnames": [
                "MessageTypeUser",
                "MessageTypeAssistant",
                "MessageTypeSystem",
                "MessageTypeTool"
            ]
        },
        "models.Provider": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "base_url": {
                    "type": "string"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_default": {
                    "type": "boolean"
                },
                "max_tokens": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "temperature": {
                    "type": "number"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "models.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {},
                "message": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "models.Session": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_active_at": {
                    "$ref": "#/definitions/models.JSONTime"
                },
                "message_count": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/models.SessionStatus"
                },
                "title": {
                    "type": "string"
                },
                "total_tokens": {
                    "type": "integer"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "models.SessionConfig": {
            "type": "object",
            "properties": {
                "enable_rate_limit": {
                    "type": "boolean"
                },
                "enable_summary": {
                    "type": "boolean"
                },
                "enable_tools": {
                    "type": "boolean"
                },
                "keep_rounds": {
                    "type": "integer"
                },
                "max_tokens": {
                    "type": "integer"
                },
                "model_id": {
                    "type": "integer"
                },
                "rate_limit_rpm": {
                    "type": "integer"
                },
                "selected_tools": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "system_prompt": {
                    "type": "string"
                },
                "temperature": {
                    "type": "number"
                }
            }
        },
        "models.SessionStatus": {
            "type": "string",
            "enum": [
                "active",
                "paused",
                "completed",
                "archived"
            ],
            "x-enum-varnames": [
                "SessionStatusActive",
                "SessionStatusPaused",
                "SessionStatusCompleted",
                "SessionStatusArchived"
            ]
        },
        "models.Tool": {
            "type": "object",
            "properties": {
                "author": {
                    "description": "作者",
                    "type": "string"
                },
                "call_count": {
                    "description": "调用次数",
                    "type": "integer"
                },
                "config": {
                    "description": "工具配置（JSON）",
                    "type": "string"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "error_count": {
                    "description": "错误次数",
                    "type": "integer"
                },
                "example": {
                    "description": "使用示例",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parameters": {
                    "description": "参数定义（JSON）",
                    "type": "string"
                },
                "returns": {
                    "description": "返回值描述",
                    "type": "string"
                },
                "script_content": {
                    "description": "脚本内容（仅对脚本工具）",
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/models.ToolStatus"
                },
                "type": {
                    "$ref": "#/definitions/models.ToolType"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                },
                "version": {
                    "description": "版本",
                    "type": "string"
                }
            }
        },
        "models.ToolStatus": {
            "type": "string",
            "enum": [
                "enabled",
                "disabled",
                "error"
            ],
            "x-enum-comments": {
                "ToolStatusDisabled": "禁用",
                "ToolStatusEnabled": "启用",
                "ToolStatusError": "错误"
            },
            "x-enum-descriptions": [
                "启用",
                "禁用",
                "错误"
            ],
            "x-enum-varnames": [
                "ToolStatusEnabled",
                "ToolStatusDisabled",
                "ToolStatusError"
            ]
        },
        "models.ToolType": {
            "type": "string",
            "enum": [
                "builtin",
                "custom",
                "external",
                "plugin",
                "script"
            ],
            "x-enum-comments": {
                "ToolTypeBuiltin": "内置工具",
                "ToolTypeCustom": "自定义工具",
                "ToolTypeExternal": "外部工具（API 调用）",
                "ToolTypePlugin": "插件工具",
                "ToolTypeScript": "脚本工具（JavaScript）"
            },
            "x-enum-descriptions": [
                "内置工具",
                "自定义工具",
                "外部工具（API 调用）",
                "插件工具",
                "脚本工具（JavaScript）"
            ],
            "x-enum-varnames": [
                "ToolTypeBuiltin",
                "ToolTypeCustom",
                "ToolTypeExternal",
                "ToolTypePlugin",
                "ToolTypeScript"
            ]
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "IANO Chat API",
	Description:      "IANO Chat 是一个智能对话系统，支持多 Agent、工具调用、流式响应等功能。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
